### ISSUE TITLE
Is Dfs robust to genomic windows?

### ISSUE THREAD

**Issue by sandyplus** [simonhmartin/dfs#1]
Dear Martin,
       
I have three species, for example, A, B, and C.
C could be the hybrid species between A and B. 
I want to know the gene flow direction and introgression time in part of the hybrid genome of C (for example, the FST islands).
Is it ok to use Dfs? Is it robust to use Dfs in genomic windows? 

Best regards,
Sandy

**Comment by simonhmartin** [comment]
Hi Sandy,
Unfortunately there is not enough information in small genomic windows to make much sense from Dfs. I would say you need tens to hundreds of thousands of variant sites, which usually requires many megabases of the genome.
Instead, I would recommend a phylogenetic approach, such as [Twisst](https://doi.org/10.1534/genetics.116.194720). We used it to identify the direction of introgression in [this study](https://www.nature.com/articles/s41467-019-13159-5).
Hope this helps,
Simon

**Comment by sandyplus** [comment]
Thanks a lot!
