### ISSUE TITLE
freq.py error

### ISSUE THREAD

**Issue by Wennie-s** [simonhmartin/dfs#2]
Hi, when I sun freq.py, there is an error：
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data/user003/soft/dfs/genomics_general-0.4/freq.py", line 55, in freqs_wrapper
    baseFreqs = popAlns[pop].siteFreqs(asCounts=asCounts)
  File "/data/user003/soft/dfs/genomics_general-0.4/genomics.py", line 1008, in siteFreqs
    return np.array([binBaseFreqs(self.numArray[:,x][self.nanMask[:,x]], asCounts=asCounts) for x in sites])
  File "/data/user003/soft/dfs/genomics_general-0.4/genomics.py", line 576, in binBaseFreqs
    if asCounts: return np.bincount(numArr, minlength=4)
MemoryError
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written
37904 slices queued | 37903 slices analysed | 37903 slices written | 106800441 lines written

When I reduced threads to 1, the same error still appears. My genome is very large (10 Gb) and I don't know why this happen. Can you help me?

**Comment by simonhmartin** [comment]
Hi, I don't think it is likely a real memory issue, as the script doesn't use much memory. I would recommend subsetting the genome into smaller files to see if it is a specific part of the genome that is causing the problem.

**Comment by Wennie-s** [comment]
> Hi, I don't think it is likely a real memory issue, as the script doesn't use much memory. I would recommend subsetting the genome into smaller files to see if it is a specific part of the genome that is causing the problem.

**Comment by Wennie-s** [comment]
Hi, Thank you for your reply. I have split my genome and solve the problem. However, the result bothers me a bit. 
![image](https://user-images.githubusercontent.com/93564905/143732947-f1b918b6-abba-4f22-8aa1-d2929a0b559b.png). The overall D value is positive, but  the highest frequency bin shows a negative Dsignal (seem to exceed -1). I’m not sure if this result is reasonable, because the value of D should be between 1 and -1.

**Comment by simonhmartin** [comment]
Hmm, that shouldn't happen. My first thoughts are:
1. Do you have the same number of individuals in both P1 and P2?
2. Did you set the number of individuals correctly in the Dfs calculation?

**Comment by Wennie-s** [comment]
> Hi, many thanks for your reply. It is indeed a problem with the number of individuals inP1 and P2, I reset it now. Another question is how to determine the parameter ''--subsample''  when running sfs.py? Is it the number of individuals in each population? （the number of individuals of P1,P2,P3 are 23, 23, 32 in my data）

**Comment by simonhmartin** [comment]
The idea is to find the best compromise between number of samples and number of sites. If you have missing data in the file (`N/N` genotypes) then this site cannot be used for computing the SFS unless your `--subsample` value for that population is lower than the total number of individuals, in which case the site could still be used. So if I had 23 individuals per population, I might subsample to about 20 per site to increase the number of sites I could include. The decision depends on the genome size (and whether you have WGS data or reduced representation) and how much missing data you have. It might be worth trying a few values and comparing the outputs.

**Comment by Wennie-s** [comment]
Thank you very much for your help. We set up different values of subsamples and recalculated according to your comments, and the results are in line with expectations.
